spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CinemaGuesser
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  forward-headers-strategy: framework
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
flyway:
  user: postgres
  password: postgres
  schemas: public
  url: jdbc:postgresql://localhost:5432/CinemaGuesser?currentSchema=public
  locations: filesystem:db/migration